package application.auth.roles;

/**
 * Created by gipai on 9/28/2017.
 */
public enum PermissionType {

    CREATE_COMPANY,
    DELETE_COMPANY,
    READ_COMPANY,
    UPDATE_COMPANY,

    CREATE_DEPARTMENT,
    DELETE_DEPARTMENT,
    READ_DEPARTMENT,
    UPDATE_DEPARTMENT,
    
    CREATE_CLIENT,
    DELETE_CLIENT,
    READ_CLIENT,
    UPDATE_CLIENT,
    
    CREATE_PHASE,
    DELETE_PHASE,
    READ_PHASE,
    UPDATE_PHASE,

    CREATE_USER,
    DELETE_USER,
    READ_USER,
    UPDATE_USER,

    CREATE_ROLE,
    DELETE_ROLE,
    READ_ROLE,
    UPDATE_ROLE,
    
    CREATE_PROJECT,
    DELETE_PROJECT,
    READ_PROJECT,
    UPDATE_PROJECT,

    CREATE_DOCUMENT,
    DELETE_DOCUMENT,
    READ_DOCUMENT,
    UPDATE_DOCUMENT;

}
